/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/users": {
    get: operations["UsersController_findAll"];
    post: operations["UsersController_create"];
  };
  "/users/{id}": {
    get: operations["UsersController_findOne"];
    delete: operations["UsersController_remove"];
    patch: operations["UsersController_update"];
  };
}

export interface components {
  schemas: {
    CreateUserDto: {
      name?: string;
      /** Format: date-time */
      bithDate?: string;
      email?: string;
      phoneNumber?: string;
    };
    City: {
      zipCode?: number;
    };
    AddressItem: {
      city?: components["schemas"]["City"];
    };
    User: {
      name?: string;
      /** Format: date-time */
      bithDate?: string;
      email?: string;
      phoneNumber?: string;
      home?: components["schemas"]["AddressItem"];
      work?: components["schemas"]["AddressItem"];
    };
    UserError: {
      /** @enum {string} */
      error: "INVALID_NAME" | "INVALID_EMAIL";
    };
    UpdateUserDto: {
      name?: string;
      /** Format: date-time */
      bithDate?: string;
      email?: string;
      phoneNumber?: string;
      home?: components["schemas"]["AddressItem"];
      work?: components["schemas"]["AddressItem"];
    };
  };
}

export interface operations {
  AppController_getHello: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  UsersController_findAll: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  UsersController_create: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["UserError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
  };
  UsersController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  UsersController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  UsersController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
  };
}

export interface external {}
